# Application
server.servlet.context-path=/api
spring.application.name=@project.parent.artifactId@

# Actuator
info.app.title=@project.parent.name@
info.app.name=@project.parent.artifactId@
info.app.version=@project.parent.version@
info.app.description=@project.parent.description@
management.info.env.enabled=true
management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.enabled=true

# Web
spring.mvc.problemdetails.enabled=true
spring.jackson.mapper.sort_properties_alphabetically=false

# Reservation Expiration Delay Config (in minutes)
reservation.expiration-delay-minutes=15

# Security
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://keycloak:8080/realms/ticket/protocol/openid-connect/certs}

# Logging
logging.level.org.springframework.security=TRACE