global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-ticket'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['ticket:8080']
