name: Build Image

on:
  workflow_call:

jobs:
  build:
    runs-on: [self-hosted, local, ticket]

    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: ./.github/actions/setup-jdk

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Push to Local Registry
        run: |
          REGISTRY="kind-registry:5000"
          docker build -t $REGISTRY/api-ticket:${{ github.sha }} .
          docker push $REGISTRY/api-ticket:${{ github.sha }}
