name: Quality Assurance

on:
  workflow_call:

jobs:
  coverage:
    runs-on: [self-hosted, local, ticket]

    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: ./.github/actions/setup-jdk

      - name: Test and SonarQube analysis
        run: |
          mvn -B clean verify sonar:sonar \
            -Dsonar.host.url=http://ticket-sonarqube:9000 \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.qualitygate.wait=true || true

  integration-tests:
    runs-on: [self-hosted, local, ticket]

    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: ./.github/actions/setup-jdk

      - name: Run integration tests
        run: mvn test -DintegrationTests=true -pl application -am
