name: Build Image

on:
  workflow_call:

jobs:
  build:
    runs-on: [self-hosted, local, ticket]

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: ./.github/actions/setup-jdk

      - name: Build Maven Application
        run: mvn clean package -DskipTests

      - name: Build and Push Image to Local Registry
        run: |
          docker build -t localhost:5001/api-ticket:${{ github.sha }} .
          docker push localhost:5001/api-ticket:${{ github.sha }}
